DEBUG_VALUE = False

DB_ENGINE = 'django.db.backends.sqlite3'
DB_NAME = 'webportal.db'
DB_USER = ''
DB_PASSWORD = ''
DB_HOST = ''
DB_PORT = ''

ALLOWED_HOST_LIST = ['localhost', '127.0.0.1']

RECAPTCHA_PUBLIC_KEY_VALUE = '6LcQ4_USAAAAAO3wR_TK3j83B4vcMZ7ZPADfAnlR' 
RECAPTCHA_PRIVATE_KEY_VALUE = '6LcQ4_USAAAAAEkjKxL4WUgi4Dw6oGNEHZWHWcuf' 
